## What are the most demand skills for the top 3 most popular data roles

#### Methodology

###### 1. Clean-up skill column 
###### 2. Calculate skill count based on job_title_short
###### 3. Calculate skill percentage
###### 4. Plot final findings

In [ ]:
import ast 
import pandas as pd 
import matplotlib.pyplot as plt 

data = pd.read_csv(r"C:\Users\Lenovo\OneDrive\Documents\Projects\Luke Barousse Projects\Python Course  Data Analysis\data_jobs.csv")
df=data
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])
df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

In [2]:
df_US = df[df['job_country'] == "United States"]

In [4]:
df_skills = df_US.explode('job_skills')
df_skills[['job_title','job_skills']]

                                   job_title  job_skills
4                     Technical Data Analyst         sql
4                     Technical Data Analyst      python
4                     Technical Data Analyst        jira
6       Research Data Scientist - Now Hiring      python
6       Research Data Scientist - Now Hiring           r
...                                      ...         ...
787623                          Data Analyst         sas
787623                          Data Analyst         sas
787623                          Data Analyst       excel
787623                          Data Analyst  powerpoint
787623                          Data Analyst     tableau

[1071299 rows x 2 columns]

In [15]:
df_skills_count=df_skills.groupby(['job_skills','job_title_short']).size()
df_skills_count = df_skills_count.reset_index(name='skill_count')

In [19]:
df_skills_count.sort_values(by='skill_count',ascending=False,inplace= True)
df_skills_count

     job_skills        job_title_short  skill_count
1207     python         Data Scientist        42497
1519        sql           Data Analyst        34504
1521        sql         Data Scientist        30073
456       excel           Data Analyst        27579
1241          r         Data Scientist        26111
...         ...                    ...          ...
619     graphql    Senior Data Analyst            1
628      groovy  Senior Data Scientist            1
623      groovy       Business Analyst            1
1838  workfront          Data Engineer            1
630         gtx           Data Analyst            1

[1869 rows x 3 columns]

In [23]:
job_title = df_skills_count['job_title_short'].unique().tolist()
job_title=sorted(job_title[:3])

In [ ]:
fig,ax = plt.subplot(len(job_titles),1)

for i,job_title in enumerate(job_titles):
    df_plot= df_skills_count[df_skills_count['job_title_short']==job_title].head(5)
    df_plot.plot(kind='barh',x='job_skills',y='skill_count',ax=ax[i],title=job_title)
    ax[i].invert_yaxis()
    ax[i].set_ylabel('')
    ax[i].legend().set_visible(Faalse)
fig.subtitle('Counts of Top Skills in Job Postings',fontsize=15)
plt.show()